# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

notifications:
  email: true

addons:
  apt:
    packages:
      - glpk-utils
      - libglpk-dev
      - libgit2-dev

r_packages:
   - covr
   - devtools

r_github_packages:
   - otrecoding/OTrecod

after_success:
   - Rscript -e 'covr::codecov()'

before_deploy: Rscript -e 'remotes::install_cran("pkgdown")'

deploy:
  provider: script
  script: Rscript -e 'pkgdown::deploy_site_github()'
  skip_cleanup: true
